/**
 * generated by Xtext 2.12.0
 */
package edu.uniandes.tour.tourdsl.ui.contentassist;

import edu.uniandes.tour.tourdsl.ui.contentassist.AbstractTourDslProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class TourDslProposalProvider extends AbstractTourDslProposalProvider {
}
