/**
 * generated by Xtext 2.12.0
 */
package edu.uniandes.tour.tourdsl.ui;

import edu.uniandes.tour.tourdsl.ui.AbstractTourDslUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class TourDslUiModule extends AbstractTourDslUiModule {
  public TourDslUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
