/**
 * generated by Xtext 2.12.0
 */
package edu.uniandes.tour.tourdsl.ide;

import edu.uniandes.tour.tourdsl.ide.AbstractTourDslIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class TourDslIdeModule extends AbstractTourDslIdeModule {
}
