/*
 * generated by Xtext 2.12.0
 */
package edu.uniandes.tour.tourdsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class TourDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("edu/uniandes/tour/tourdsl/parser/antlr/internal/InternalTourDsl.tokens");
	}
}
