/*
 * generated by Xtext 2.12.0
 */
package edu.uniandes.tour.tourdsl.parser.antlr;

import com.google.inject.Inject;
import edu.uniandes.tour.tourdsl.parser.antlr.internal.InternalTourDslParser;
import edu.uniandes.tour.tourdsl.services.TourDslGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class TourDslParser extends AbstractAntlrParser {

	@Inject
	private TourDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalTourDslParser createParser(XtextTokenStream stream) {
		return new InternalTourDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Tour";
	}

	public TourDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(TourDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
