/**
 * generated by Xtext 2.12.0
 */
package edu.uniandes.tour.tourdsl.formatting2;

import com.google.inject.Inject;
import edu.uniandes.tour.tourdsl.services.TourDslGrammarAccess;
import java.util.Arrays;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;
import projectTour.Hotspot;
import projectTour.Panorama;
import projectTour.Tour;

@SuppressWarnings("all")
public class TourDslFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private TourDslGrammarAccess _tourDslGrammarAccess;
  
  protected void _format(final Tour tour, @Extension final IFormattableDocument document) {
    EList<Panorama> _panorama = tour.getPanorama();
    for (final Panorama panorama : _panorama) {
      document.<Panorama>format(panorama);
    }
  }
  
  protected void _format(final Panorama panorama, @Extension final IFormattableDocument document) {
    EList<Hotspot> _hotspot = panorama.getHotspot();
    for (final Hotspot hotspot : _hotspot) {
      document.<Hotspot>format(hotspot);
    }
  }
  
  public void format(final Object panorama, final IFormattableDocument document) {
    if (panorama instanceof XtextResource) {
      _format((XtextResource)panorama, document);
      return;
    } else if (panorama instanceof Panorama) {
      _format((Panorama)panorama, document);
      return;
    } else if (panorama instanceof Tour) {
      _format((Tour)panorama, document);
      return;
    } else if (panorama instanceof EObject) {
      _format((EObject)panorama, document);
      return;
    } else if (panorama == null) {
      _format((Void)null, document);
      return;
    } else if (panorama != null) {
      _format(panorama, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(panorama, document).toString());
    }
  }
}
