/*
 * generated by Xtext 2.12.0
 */
package edu.uniandes.tour.tourdsl.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith
import projectTour.Tour

@RunWith(XtextRunner)
@InjectWith(TourDslInjectorProvider)
class TourDslParsingTest {
	@Inject
	ParseHelper<Tour> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
		Assert.assertTrue(result.eResource.errors.isEmpty)
	}
}
