/*
 * generated by Xtext 2.12.0
 */
package edu.uniandes.tour.tourdsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class TourDslStandaloneSetup extends TourDslStandaloneSetupGenerated {

	def static void doSetup() {
		new TourDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
