/*
 * generated by Xtext 2.12.0
 */
package edu.uniandes.tour.tourdsl.ui.tests;

import com.google.inject.Injector;
import edu.uniandes.tour.tourdsl.ui.internal.TourdslActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class TourDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return TourdslActivator.getInstance().getInjector("edu.uniandes.tour.tourdsl.TourDsl");
	}

}
