/**
 * generated by Xtext 2.12.0
 */
package edu.uniandes.tour.tourdsl;

import edu.uniandes.tour.tourdsl.TourDslStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class TourDslStandaloneSetup extends TourDslStandaloneSetupGenerated {
  public static void doSetup() {
    new TourDslStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
