/**
 * generated by Xtext 2.12.0
 */
package edu.uniandes.tour.tourdsl;

import edu.uniandes.tour.tourdsl.AbstractTourDslRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class TourDslRuntimeModule extends AbstractTourDslRuntimeModule {
}
