/*
 * generated by Xtext 2.12.0
 */
package edu.uniandes.tour.tourdsl.ide.contentassist.antlr;

import com.google.inject.Inject;
import edu.uniandes.tour.tourdsl.ide.contentassist.antlr.internal.InternalTourDslParser;
import edu.uniandes.tour.tourdsl.services.TourDslGrammarAccess;
import java.util.HashMap;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class TourDslParser extends AbstractContentAssistParser {

	@Inject
	private TourDslGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalTourDslParser createParser() {
		InternalTourDslParser result = new InternalTourDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getEDoubleAccess().getAlternatives_4_0(), "rule__EDouble__Alternatives_4_0");
					put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
					put(grammarAccess.getTourAccess().getGroup(), "rule__Tour__Group__0");
					put(grammarAccess.getPanoramaAccess().getGroup(), "rule__Panorama__Group__0");
					put(grammarAccess.getHotspotAccess().getGroup(), "rule__Hotspot__Group__0");
					put(grammarAccess.getRotationAccess().getGroup(), "rule__Rotation__Group__0");
					put(grammarAccess.getPositionAccess().getGroup(), "rule__Position__Group__0");
					put(grammarAccess.getEDoubleAccess().getGroup(), "rule__EDouble__Group__0");
					put(grammarAccess.getEDoubleAccess().getGroup_4(), "rule__EDouble__Group_4__0");
					put(grammarAccess.getTourAccess().getNameAssignment_4(), "rule__Tour__NameAssignment_4");
					put(grammarAccess.getTourAccess().getPanoramaAssignment_9(), "rule__Tour__PanoramaAssignment_9");
					put(grammarAccess.getPanoramaAccess().getNameAssignment_4(), "rule__Panorama__NameAssignment_4");
					put(grammarAccess.getPanoramaAccess().getDescriptionAssignment_8(), "rule__Panorama__DescriptionAssignment_8");
					put(grammarAccess.getPanoramaAccess().getHotspotAssignment_13(), "rule__Panorama__HotspotAssignment_13");
					put(grammarAccess.getHotspotAccess().getNameAssignment_4(), "rule__Hotspot__NameAssignment_4");
					put(grammarAccess.getHotspotAccess().getToAssignment_8(), "rule__Hotspot__ToAssignment_8");
					put(grammarAccess.getHotspotAccess().getPositionAssignment_10(), "rule__Hotspot__PositionAssignment_10");
					put(grammarAccess.getHotspotAccess().getRotationAssignment_12(), "rule__Hotspot__RotationAssignment_12");
					put(grammarAccess.getRotationAccess().getXAssignment_6(), "rule__Rotation__XAssignment_6");
					put(grammarAccess.getRotationAccess().getYAssignment_10(), "rule__Rotation__YAssignment_10");
					put(grammarAccess.getRotationAccess().getZAssignment_14(), "rule__Rotation__ZAssignment_14");
					put(grammarAccess.getPositionAccess().getXAssignment_6(), "rule__Position__XAssignment_6");
					put(grammarAccess.getPositionAccess().getYAssignment_10(), "rule__Position__YAssignment_10");
					put(grammarAccess.getPositionAccess().getZAssignment_14(), "rule__Position__ZAssignment_14");
				}
			};
		}
		return nameMappings.get(element);
	}
			
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public TourDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(TourDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
