/*
 * generated by Xtext 2.12.0
 */
package edu.uniandes.tour.tourdsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractTourDslScopeProvider extends DelegatingScopeProvider {
}
