/**
 * generated by Xtext 2.12.0
 */
package edu.uniandes.tour.tourdsl.tests;

import com.google.inject.Inject;
import edu.uniandes.tour.tourdsl.tests.TourDslInjectorProvider;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.XtextRunner;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import projectTour.Tour;

@RunWith(XtextRunner.class)
@InjectWith(TourDslInjectorProvider.class)
@SuppressWarnings("all")
public class TourDslParsingTest {
  @Inject
  private ParseHelper<Tour> parseHelper;
  
  @Test
  public void loadModel() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("Hello Xtext!");
      _builder.newLine();
      final Tour result = this.parseHelper.parse(_builder);
      Assert.assertNotNull(result);
      Assert.assertTrue(result.eResource().getErrors().isEmpty());
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
