/*
 * generated by Xtext 2.12.0
 */
package edu.uniandes.tour.tourdsl.ui;

import com.google.inject.Injector;
import edu.uniandes.tour.tourdsl.ui.internal.TourdslActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TourDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return TourdslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return TourdslActivator.getInstance().getInjector(TourdslActivator.EDU_UNIANDES_TOUR_TOURDSL_TOURDSL);
	}
	
}
